# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-02 01:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='media',
            field=models.ManyToManyField(to='blog.Media'),
        ),
        migrations.AlterField(
            model_name='media',
            name='full_image',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='full/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='media',
            name='scale_image',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='scale/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(unique_for_date='pub_date'),
        ),
    ]
