# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_media_thumb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='image',
        ),
        migrations.AddField(
            model_name='media',
            name='full_image',
            field=models.ImageField(default='meh', upload_to='full/%Y/%m/%d'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='media',
            name='post_image',
            field=models.ImageField(default='meh', upload_to='posts/%Y/%m/%d'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='media',
            name='thumb',
            field=models.ImageField(default='meh', upload_to='thumbs/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
