# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-02 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160601_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body_html',
            field=models.TextField(blank=True, null=True),
        ),
    ]
