# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-07 19:36
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models
import django.utils.timezone
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160720_2022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['slug'], 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterField(
            model_name='media',
            name='full_image',
            field=versatileimagefield.fields.VersatileImageField(max_length=200, upload_to='full/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='media',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='media',
            name='scale_image',
            field=versatileimagefield.fields.VersatileImageField(max_length=200, upload_to='scale/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=blog.models.default_start_time, verbose_name='date published'),
        ),
    ]
