# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-02 01:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_body_html'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'ordering': ['post_order'], 'verbose_name_plural': 'media'},
        ),
        migrations.AddField(
            model_name='media',
            name='post_order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
