# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 01:26
from __future__ import unicode_literals

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160124_2007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'verbose_name_plural': 'Media'},
        ),
        migrations.RemoveField(
            model_name='media',
            name='post_image',
        ),
        migrations.RemoveField(
            model_name='media',
            name='thumb',
        ),
        migrations.AlterField(
            model_name='media',
            name='full_image',
            field=versatileimagefield.fields.VersatileImageField(upload_to='versatile/%Y/%m/%d'),
        ),
    ]
