# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-13 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20160601_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='full_image',
            field=models.ImageField(default='meh', max_length=200, upload_to='full/%Y/%m/%d'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='media',
            name='scale_image',
            field=models.ImageField(default='meh', max_length=200, upload_to='scale/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
