# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-11 13:48
from __future__ import unicode_literals

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20160807_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='first_image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to=''),
        ),
    ]
