# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-11 14:00
from __future__ import unicode_literals

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_first_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='first_image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, max_length=200, null=True, upload_to=''),
        ),
    ]
