# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-22 03:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20160520_1704'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Media',
        ),
        migrations.RemoveField(
            model_name='post',
            name='thumb',
        ),
    ]
