# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-13 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20160613_1813'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'ordering': ['image_name'], 'verbose_name_plural': 'media'},
        ),
        migrations.RemoveField(
            model_name='media',
            name='post_order',
        ),
        migrations.RemoveField(
            model_name='post',
            name='media',
        ),
        migrations.AddField(
            model_name='media',
            name='image_name',
            field=models.CharField(default='meh1', max_length=200),
            preserve_default=False,
        ),
    ]
