# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-23 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20160521_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_image', models.ImageField(blank=True, null=True, upload_to=b'full/%Y/%m/%d')),
                ('scale_image', models.ImageField(blank=True, null=True, upload_to=b'scale/%Y/%m/%d')),
            ],
        ),
    ]
