# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-13 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20160613_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='image_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
