# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-14 00:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20160613_1842'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'ordering': ['-pub_date'], 'verbose_name_plural': 'media'},
        ),
        migrations.AddField(
            model_name='media',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
        ),
    ]
