# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-23 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='full_image',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=b'full/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='media',
            name='scale_image',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=b'scale/%Y/%m/%d'),
        ),
    ]
