# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20160901_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=300, unique_for_date='pub_date'),
        ),
    ]
