# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-04 14:22
from __future__ import unicode_literals

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20160901_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='scale_image',
            field=versatileimagefield.fields.VersatileImageField(default='', editable=False, max_length=200, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='body_html',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='first_image',
            field=versatileimagefield.fields.VersatileImageField(default='', editable=False, max_length=200, upload_to=''),
            preserve_default=False,
        ),
    ]
