# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-04 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20160904_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body_html',
            field=models.TextField(editable=False),
        ),
    ]
